// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZ-YnmmzG-ycxmU5uJJw0a3ZcVV-jqqo',
    appId: '1:266737849674:web:554d2958bf8dff651e5db3',
    messagingSenderId: '266737849674',
    projectId: 'isimm-intern',
    authDomain: 'isimm-intern.firebaseapp.com',
    storageBucket: 'isimm-intern.firebasestorage.app',
    measurementId: 'G-SNBT1X9V7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjF1ZbA0FQXVkwGLWYJBCkbQjvruziO_s',
    appId: '1:266737849674:android:bc47a9d349a85c741e5db3',
    messagingSenderId: '266737849674',
    projectId: 'isimm-intern',
    storageBucket: 'isimm-intern.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9ypRtt24fhml3TO30eG9V_lpj-zHtKI',
    appId: '1:266737849674:ios:775ae4fc39cfbc621e5db3',
    messagingSenderId: '266737849674',
    projectId: 'isimm-intern',
    storageBucket: 'isimm-intern.firebasestorage.app',
    androidClientId:
        '266737849674-6r322emcom0bf9mfrjq0nthl02cb6svq.apps.googleusercontent.com',
    iosClientId:
        '266737849674-edeukpvc5crgj0rb9or29llkbrmmsli9.apps.googleusercontent.com',
    iosBundleId: 'tech.chedy.projects.isimm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBZ-YnmmzG-ycxmU5uJJw0a3ZcVV-jqqo',
    appId: '1:266737849674:web:3d276fc1bd36e4891e5db3',
    messagingSenderId: '266737849674',
    projectId: 'isimm-intern',
    authDomain: 'isimm-intern.firebaseapp.com',
    storageBucket: 'isimm-intern.firebasestorage.app',
    measurementId: 'G-4ESVF9J0PM',
  );
}
